name: Advanced Contribution Tracker
on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ main ]  # Runs on push to main branch

jobs:
  update-contribution:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.31.0 PyGithub==2.1.1

      - name: Generate contribution stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          mkdir -p dist
          python << 'EOF'
          import os
          import json
          from datetime import datetime
          from github import Github
          
          # Initialize GitHub client
          token = os.environ['GITHUB_TOKEN']
          username = os.environ['GITHUB_REPOSITORY_OWNER']
          
          g = Github(token)
          user = g.get_user(username)
          
          # Get current stats
          stats = {
              'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
              'username': username,
              'public_repos': user.public_repos,
              'followers': user.followers,
              'following': user.following,
              'latest_activity': []
          }
          
          # Get recent activity
          try:
              events = list(user.get_events()[:10])
              for event in events:
                  stats['latest_activity'].append({
                      'type': event.type,
                      'repo': event.repo.name if event.repo else 'Unknown',
                      'created_at': event.created_at.strftime('%Y-%m-%d %H:%M:%S')
                  })
          except Exception as e:
              print(f"Error fetching events: {e}")
          
          # Save stats
          with open('dist/contribution_stats.json', 'w') as f:
              json.dump(stats, f, indent=2)
          
          # Create summary
          with open('dist/summary.md', 'w') as f:
              f.write(f"# Contribution Summary for {username}\n\n")
              f.write(f"Last updated: {stats['timestamp']}\n\n")
              f.write(f"- Public Repositories: {stats['public_repos']}\n")
              f.write(f"- Followers: {stats['followers']}\n")
              f.write(f"- Following: {stats['following']}\n\n")
              f.write("## Recent Activity\n\n")
              for activity in stats['latest_activity']:
                  f.write(f"- {activity['type']} in {activity['repo']} at {activity['created_at']}\n")
          
          print("Stats generated successfully!")
          EOF

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=blue&color_dots=#161b22,#0a4208,#006d32,#26a641,#39d353

      - name: Generate HTML dashboard
        run: |
          cat > dist/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>GitHub Contribution Dashboard</title>
              <script src="https://cdn.tailwindcss.com"></script>
              <style>
                  @keyframes fadeIn {
                      from { opacity: 0; transform: translateY(10px); }
                      to { opacity: 1; transform: translateY(0); }
                  }
                  .fade-in {
                      animation: fadeIn 0.5s ease-out;
                  }
              </style>
          </head>
          <body class="bg-gray-900 text-white p-8">
              <div class="max-w-6xl mx-auto">
                  <h1 class="text-4xl font-bold mb-8 text-center bg-gradient-to-r from-blue-400 to-purple-600 bg-clip-text text-transparent">
                      GitHub Activity Dashboard
                  </h1>
                  
                  <!-- Stats Cards -->
                  <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                      <div class="bg-gray-800 p-6 rounded-lg border border-gray-700 fade-in">
                          <h3 class="text-gray-400 text-sm mb-2">Public Repos</h3>
                          <p class="text-3xl font-bold" id="repo-count">-</p>
                      </div>
                      <div class="bg-gray-800 p-6 rounded-lg border border-gray-700 fade-in">
                          <h3 class="text-gray-400 text-sm mb-2">Followers</h3>
                          <p class="text-3xl font-bold" id="follower-count">-</p>
                      </div>
                      <div class="bg-gray-800 p-6 rounded-lg border border-gray-700 fade-in">
                          <h3 class="text-gray-400 text-sm mb-2">Following</h3>
                          <p class="text-3xl font-bold" id="following-count">-</p>
                      </div>
                  </div>
                  
                  <!-- Contribution Snake -->
                  <div class="bg-gray-800 p-6 rounded-lg border border-gray-700 mb-8 fade-in">
                      <h2 class="text-2xl font-semibold mb-4 text-center">Contribution Activity</h2>
                      <img src="github-contribution-grid-snake-dark.svg" alt="Contribution Graph" class="w-full rounded">
                  </div>
                  
                  <!-- Activity Feed -->
                  <div class="bg-gray-800 p-6 rounded-lg border border-gray-700 fade-in">
                      <h2 class="text-2xl font-semibold mb-4">Recent Activity</h2>
                      <div id="activity-feed" class="space-y-3">
                          <div class="animate-pulse">
                              <div class="h-4 bg-gray-700 rounded w-3/4 mb-2"></div>
                              <div class="h-4 bg-gray-700 rounded w-1/2"></div>
                          </div>
                      </div>
                  </div>
                  
                  <div class="text-sm text-gray-400 text-center mt-8">
                      Last updated: <span id="last-updated">Loading...</span>
                  </div>
              </div>
              
              <script>
                  fetch('contribution_stats.json')
                      .then(response => response.json())
                      .then(data => {
                          document.getElementById('last-updated').textContent = data.timestamp;
                          document.getElementById('repo-count').textContent = data.public_repos;
                          document.getElementById('follower-count').textContent = data.followers;
                          document.getElementById('following-count').textContent = data.following;
                          
                          const feed = document.getElementById('activity-feed');
                          feed.innerHTML = data.latest_activity
                              .map((activity, index) => `
                                  <div class="p-4 bg-gray-700 rounded-lg transition-all hover:bg-gray-600 fade-in" style="animation-delay: ${index * 0.1}s">
                                      <div class="flex items-center justify-between">
                                          <div>
                                              <div class="font-semibold text-blue-400">${activity.type.replace(/([A-Z])/g, ' $1').trim()}</div>
                                              <div class="text-sm text-gray-300">${activity.repo}</div>
                                          </div>
                                          <div class="text-xs text-gray-400">${new Date(activity.created_at).toRelaleString()}</div>
                                      </div>
                                  </div>
                              `)
                              .join('');
                      })
                      .catch(error => {
                          console.error('Error loading stats:', error);
                          document.getElementById('activity-feed').innerHTML = '<p class="text-red-400">Error loading activity feed</p>';
                      });
              </script>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages  # Changed from 'output' to standard 'gh-pages'
          force_orphan: true
          enable_jekyll: false
          commit_message: "🤖 Update contribution dashboard [skip ci]"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
